name: ci 
on:
  push:
    branches:
      - master 
      - main
  # At minute 0 past every 6th hour
  # schedule:
  # - cron: "0 */6 * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # - uses: actions/checkout@v2
      # - name: Checkout submodules
      #   shell: bash
      #   run: |
      #     git config --global user.email "you@example.com"
      #     git config --global user.name "Your Name"
      #     git config --global pull.rebase false
      #     git submodule add https://github.com/swisskyrepo/HardwareAllTheThings docs

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-committers-plugin
      - run: pip install mkdocs-material[imaging]
      - run: pip install mkdocs-meta-descriptions-plugin
      - run: mkdocs gh-deploy --force

